spring:
  profiles: local

  datasource:
    url: jdbc:mysql://localhost:3306/parkingsystem
    username: root
    password: 1234

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false


server:
  port: 8080